import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execFile, execFileSync } from "node:child_process";
import { promisify } from "node:util";

// Profile and checkout preparation for an agent terminal: the mission-control skill in a CLI config
// dir, the `mc` CLI in ~/.mc/bin, and the AGENTS.md mirror (+ local-only git excludes) in a checkout.
//
// Moved out of terminal.ts unchanged so `chronos host` (HOSTS.md phase 3, `prepare()`) runs the SAME
// code on its own filesystem. terminal.ts imports the store; this module must not, because a host
// must never open a Chronos database. `root` is where `skills/` and `scripts/` live — the daemon's
// cwd on the brain (what it always was), the host's checkout on a host (whose cwd is ~/.chronos-host).

// Install the "mission-control" Claude skill into a config dir so every claude agent spawned with that
// CLAUDE_CONFIG_DIR auto-knows the `mc` workflow (tickets, jobs, notes, review). Idempotent.
// (Cursor doesn't read Claude skills — those sessions rely on the seed/goal prompt instead.)
export function installMcSkill(configDir: string, root = process.cwd()) {
  try {
    const src = path.join(root, "skills", "mission-control", "SKILL.md");
    if (!fs.existsSync(src) || !configDir) return;
    const dir = path.join(configDir, "skills", "mission-control");
    fs.mkdirSync(dir, { recursive: true });
    fs.copyFileSync(src, path.join(dir, "SKILL.md"));
  } catch (e: any) {
    console.warn("[terminal] mc skill install failed:", e?.message ?? e);
  }
}

// Cursor (and other CLIs) read AGENTS.md from the repo root, not Claude skills. Mirror the
// mission-control skill body into each repo's AGENTS.md so cursor agents get the same MC workflow.
// Kept IN SYNC with skills/mission-control/SKILL.md: regenerated at boot + on every session open.
const AGENTS_BEGIN = "<!-- BEGIN mission-control (auto-generated by Chronos; in sync with the mission-control skill — do not edit) -->";
const AGENTS_END = "<!-- END mission-control -->";

const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

// Skill markdown minus its frontmatter — the shared source of truth for both the skill and AGENTS.md.
function mcSkillBody(root = process.cwd()): string {
  try {
    const raw = fs.readFileSync(path.join(root, "skills", "mission-control", "SKILL.md"), "utf8");
    const m = raw.match(/^---\n[\s\S]*?\n---\n?([\s\S]*)$/);
    return (m ? m[1] : raw).trim();
  } catch {
    return "";
  }
}

const execFileAsync = promisify(execFile);

// `git rev-parse --git-path info/exclude` resolves the real per-checkout exclude file whether
// `repoPath` is a normal checkout (returns a path relative to repoPath, e.g. ".git/info/exclude")
// or a worktree (.git is a FILE there — git returns an absolute path into the main repo's
// .git/worktrees/<name>/info/exclude instead). Exported for testing the resolution alone.
export async function gitExcludePath(repoPath: string): Promise<string> {
  const { stdout } = await execFileAsync("git", ["-C", repoPath, "rev-parse", "--git-path", "info/exclude"], {
    encoding: "utf8",
    timeout: 5000,
  });
  const p = stdout.trim();
  return path.isAbsolute(p) ? p : path.join(repoPath, p);
}

// Is this directory inside a git checkout at all? Asked once per sync so the artifact loop below
// doesn't spend a failing subprocess (and a scary log line) per artifact on a plain directory.
// Exported for testing the check alone.
export async function insideGitRepo(dir: string): Promise<boolean> {
  try {
    const { stdout } = await execFileAsync("git", ["-C", dir, "rev-parse", "--is-inside-work-tree"], {
      encoding: "utf8",
      timeout: 5000,
    });
    return stdout.trim() === "true";
  } catch {
    return false;
  }
}

// Append a local-only ignore (never committed) so a generated AGENTS.md doesn't pollute the repo.
// Never throws: a failure here (not a git repo, git missing, timeout) must not block AGENTS.md sync.
async function gitExcludeLocal(repoPath: string, line: string): Promise<void> {
  try {
    const ex = await gitExcludePath(repoPath);
    fs.mkdirSync(path.dirname(ex), { recursive: true });
    const cur = fs.existsSync(ex) ? fs.readFileSync(ex, "utf8") : "";
    if (!cur.split("\n").includes(line)) fs.writeFileSync(ex, cur.replace(/\n?$/, "\n") + line + "\n");
  } catch (e: any) {
    // A cwd that is not a checkout is ORDINARY, not a failure: the umbrella directory that holds
    // several repos (~/Documents/GitHub/acme) is a normal place to open a terminal, and there
    // is no exclude file to write there. It logged a two-line git fatal per artifact per session
    // open. Everything else — git missing, a timeout, a read-only .git — still gets said out loud.
    const msg = String(e?.stderr ?? e?.message ?? e);
    if (/not a git repository/i.test(msg)) return;
    console.warn("[terminal] AGENTS.md git-exclude failed:", msg);
  }
}

// Is `rel` tracked by git in this checkout? `--error-unmatch` exits non-zero for an untracked path,
// so every failure mode (untracked, not a repo, git missing, timeout) answers "not tracked" — the
// same permissive answer the pre-existing code gave, which keeps non-git repo dirs working.
//
// Deliberately SYNCHRONOUS, and it must stay that way. execute() (runner.ts) needs this answer to
// assemble append_system, and everything before its `liveSteer.set` registration has to stay
// await-free — dispatch() returns mid-prologue, so a steer arriving during any earlier await
// bounces to the mailbox instead of the queue. Making this a promise hung four steer/park tests.
export function gitTrackedSync(repoPath: string, rel: string): boolean {
  try {
    const out = execFileSync("git", ["-C", repoPath, "ls-files", "--error-unmatch", "--", rel], {
      encoding: "utf8",
      timeout: 5000,
      stdio: ["ignore", "pipe", "ignore"],
    });
    return out.trim().length > 0;
  } catch {
    return false;
  }
}

// The mission-control workflow as standing system text, for callers that can't use the file mirror
// below (see syncAgentsMd's tracked-file bail-out). Empty string when the skill body is unreadable.
export function mcSystemText(): string {
  return mcSkillBody();
}

// Everything Chronos writes INSIDE a repo working tree. Chronos is a purely local tool: none of it
// may ever reach a repo's history, and `git add -A` (which Chronos itself runs three times on the
// way to a PR, and which humans run constantly) stages untracked files too. So every artifact gets
// a local-only ignore in every repo, refreshed on the same schedule as the AGENTS.md sync.
//
// `.mc/` holds ticket markdown, written under repo.path by resolveFilePath (tickets.ts). It had no
// ignore at all: six of them were committed into the presence repo before this landed.
const CHRONOS_ARTIFACTS = [".mc/"];

// Local-only ignores for Chronos's in-repo artifacts. An artifact that is ALREADY tracked can't be
// fixed from here — `info/exclude` is ignored for paths in the index — so that case is surfaced
// loudly instead of silently doing nothing; it needs a `git rm --cached` in the repo.
export async function excludeChronosArtifacts(repoPath: string): Promise<void> {
  if (!(await insideGitRepo(repoPath))) return; // nothing to exclude from — see gitExcludeLocal
  for (const art of CHRONOS_ARTIFACTS) {
    try {
      if (gitTrackedSync(repoPath, art.replace(/\/$/, ""))) {
        console.warn(
          `[terminal] ${repoPath}: ${art} is TRACKED by the repo — local exclude cannot help. ` +
            `Run: git -C ${repoPath} rm -r --cached ${art}`
        );
        continue;
      }
      await gitExcludeLocal(repoPath, art);
    } catch (e: any) {
      console.warn(`[terminal] ${repoPath}: exclude ${art} failed:`, e?.message ?? e);
    }
  }
}

// Write/refresh the mission-control managed block in <repo>/AGENTS.md, preserving any existing
// content. Called on PTY session open, daemon boot, and (via runner.ts) before every headless build
// spawn — headless runs execute in a git worktree, which never has the untracked AGENTS.md a normal
// checkout accumulates over time.
//
// NEVER touches an AGENTS.md the repo itself tracks. `info/exclude` has no effect on a path already
// in the index, so appending the block to a tracked file is a real modification, and Chronos runs
// `git add -A` in three places on the way to a PR (captureDiff, createForRun, shipPR in reviews.ts)
// — the block shipped into presence's history that way (60a891b) and was one dispatch away from a
// 346-line diff on a client repo's PR. It also left every such shared checkout permanently dirty,
// which is enough on its own to make landCommitDelivery refuse to land. Returns what it did so the
// caller can route the same content through a channel that touches no file (runner.ts).
export async function syncAgentsMd(repoPath: string, root = process.cwd(), home = os.homedir()): Promise<"written" | "skipped-tracked" | "noop"> {
  try {
    if (!repoPath || repoPath === home || !fs.existsSync(repoPath)) return "noop";
    // Runs on every call, independent of the AGENTS.md outcome below: this is the one function all
    // three call sites (boot, PTY open, pre-spawn) already share, so it's where the repo-shielding
    // ignores belong. Keeping it above every early return is the point.
    await excludeChronosArtifacts(repoPath);
    const body = mcSkillBody(root);
    if (!body) return "noop";
    if (gitTrackedSync(repoPath, "AGENTS.md")) return "skipped-tracked";
    const block = `${AGENTS_BEGIN}\n${body}\n${AGENTS_END}`;
    const file = path.join(repoPath, "AGENTS.md");
    const prev = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : "";
    let next: string;
    if (prev.includes(AGENTS_BEGIN) && prev.includes(AGENTS_END)) {
      next = prev.replace(new RegExp(`${escapeRe(AGENTS_BEGIN)}[\\s\\S]*?${escapeRe(AGENTS_END)}`), block);
    } else if (prev.trim()) {
      next = `${prev.trimEnd()}\n\n${block}\n`; // append; never clobber the repo's own AGENTS.md
    } else {
      next = `${block}\n`;
    }
    if (next !== prev) fs.writeFileSync(file, next);
    // Exclude on EVERY untracked write, not just the first-create it used to guard on: a
    // pre-existing untracked AGENTS.md (a human's scratch copy, or one this daemon wrote before the
    // exclude step existed) was never excluded, so the generated block still showed up in
    // `git status` — and `add -A` stages untracked files too.
    await gitExcludeLocal(repoPath, "AGENTS.md");
    return "written";
  } catch (e: any) {
    console.warn("[terminal] AGENTS.md sync failed:", e?.message ?? e);
    return "noop";
  }
}

// Install the `mc` agent CLI to ~/.mc/bin (a neutral path the per-workspace sandbox allows). Source
// of truth is scripts/mc in the repo; copy it out so spawned agents can call `mc` via PATH.
export function installMcCli(root = process.cwd(), home = os.homedir()) {
  try {
    const src = path.join(root, "scripts", "mc");
    if (!fs.existsSync(src)) return;
    const dir = path.join(home, ".mc", "bin");
    fs.mkdirSync(dir, { recursive: true });
    const dst = path.join(dir, "mc");
    fs.copyFileSync(src, dst);
    fs.chmodSync(dst, 0o755);
  } catch (e: any) {
    console.warn("[terminal] mc CLI install failed:", e?.message ?? e);
  }
}
